Add onLayout dev standard
bamlab/dev-standards pull request #110
Opened 2018-03-12 17:09 UTC by juliennassar

2018-03-13 09:07 UTC, tychota approved these changes

2018-03-13 09:07 UTC, tychota commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +If you need to create a loading bar or display a list of elements without previous knowlegde of the size of these elements and you want them to be all the same, you need to know the width, height or
Ca manque d'une image !

2018-03-13 09:07 UTC, tychota commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +
https://bamtech.gitbook.io/dev-standards/ops/mo-setup-https-on-your-docker-environment#control-points

2018-03-13 09:07 UTC, tychota commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +To do this, React offers a onLayout props in which you can pass a callback that will be executed after the rendering of a component.
`onLayout`

2018-03-13 09:07 UTC, tychota commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +        {// Some react component to display whatever}
{/* Some react component to display whatever */}

2018-03-13 09:07 UTC, tychota commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +Here we have a component to dsplay te loader :
Prerequisite ?

2018-03-13 09:07 UTC, tychota commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +      {// Here you want to display x% of your bar, x being the props 'status' passed by the component above}
Idem comment

2018-03-13 10:27 UTC, louiszawadzki requested changes
typos

2018-03-13 10:27 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +If you need to create a loading bar or display a list of elements without previous knowlegde of the size of these elements and you want them to be all the same, you need to know the width, height or
'.' missing

2018-03-13 10:27 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +If you need to create a loading bar or display a list of elements without previous knowlegde of the size of these elements and you want them to be all the same, you need to know the width, height or
Try to break this into more than one sentence or make a list

2018-03-13 10:27 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +If you need to create a loading bar or display a list of elements without previous knowlegde of the size of these elements and you want them to be all the same, you need to know the width, height or
Typo : "cariables" instead of "variables"

2018-03-13 10:27 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +If you need to create a loading bar or display a list of elements without previous knowlegde of the size of these elements and you want them to be all the same, you need to know the width, height or
Pro tip to facilitate code review: no more than one sentence per line ;)

2018-03-13 10:27 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +your goal is to calculate the number of green pixels rows you have to display for a given loading status from 0 (0%) to 1 (100%) without previous knowlegde of the loader width
missing dot at the end

2018-03-13 10:27 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +Here we have a component to dsplay te loader :
typos: dsplay te  -> display the

2018-03-17 14:44 UTC, louiszawadzki commented on README.MD
> +- [[MO] get a Compenent size or position with onLayout](/react-native/react/get-element-size-or-position-with-onLayout.mo.md)
Get a component size or position with onLayout

2018-03-17 14:51 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +Voilà !
I  ended my first article with "Voilà" too.
I think about 90% of French devs do just the same.
I feel it's like putting [Benny Hill's theme](https://www.youtube.com/watch?v=MK6TXMsvgQg) over a funny video: the first time you see it it is ok but when you realize everybody does this you find out it's really too easy and a bit lazy ^^

So please change this. Happy to discuss if you disagree.

2018-03-17 14:52 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +First add a function to your `LoadingBar` component to get its width, and pass it in the `onLayout` props of your `LoadingBar` Component, and store it in your component's state :
Can you add a link to the official RN docs ? https://facebook.github.io/react-native/docs/view.html#onlayout

2018-03-17 14:56 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +the `onLayout` will generate an event when the LoadingBar is displayed. You can access any layouts info with :
Capitalize the beginning of the sentence

2018-03-17 14:56 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +the `onLayout` will generate an event when the LoadingBar is displayed. You can access any layouts info with :
Any layout* info

2018-03-17 14:57 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +you can know calculate the number of green pixels rows with the width we just got with `onLayout` :
Capitalize the beginning of the sentence

2018-03-17 14:59 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +you can know calculate the number of green pixels rows with the width we just got with `onLayout` :
Use "compute" instead of "calculate"

2018-03-17 14:59 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +
Can you show the final component ?

2018-03-17 15:00 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +- Hide your dynamically sized (or positioned) component width a `style={{ opacity: 0 }}` during the first rendering of your component to avoid glitches.
I would rather add this to a troubleshooting part

2018-03-17 15:03 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +Voilà !
You could end your article like

> And this is what the final version of your component should look like:

2018-03-17 15:05 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +A react/react-native app with components. We will take here the example of a loading bar like this one :
A React Native app (the use of components is implicit).

This does not work on React as `onLayout` only exists in React Native components.

2018-03-17 15:22 UTC, louiszawadzki commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +- to create a custom loading bar display
Why do you actually want to use onLayout to do this? You can do without it using the a percentage width: https://snack.expo.io/@louiszawadzki/loading-bar.

I have no proof but I believe using onLayout could be slower (or at least demand more computation) than using styles.

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +- Hide your dynamically sized (or positioned) component width a `style={{ opacity: 0 }}` during the first rendering of your component to avoid glitches.
with

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +- just to know the size or position of an element on your screen dynamically (whithout explicitly describing it the object's style)
to know

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +- just to know the size or position of an element on your screen dynamically (whithout explicitly describing it the object's style)
without explicitly describing it in the object's style

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +You must have access those variables during the runtime of your application.
Pas utile à la compréhension

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +Your goal is to calculate the number of green pixels rows you have to display for a given loading status from 0 (0%) to 1 (100%) without previous knowlegde of the loader width :
knowledge

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +    <View onLayout={this.getLoadingBarWidth}>
measureLoadingBar

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +  getLoadingBarWidth = event => this.setState({loaderWidth: event.nativeEvent.layout.width })
measureLoadingBar = ({nativeEvent}) => this.setState({ loaderWidth: nativeEvent.layout.width });

2018-07-27 12:24 UTC, Minishlink commented on react-native/react/get-element-size-or-position-with-onLayout.mo.md
> +You can know compute the number of green pixels rows with the width we just got with `onLayout` :
now

2018-07-30 12:30 UTC, merged