add performance standards
bamlab/dev-standards pull request #118
Opened 2018-04-05 12:15 UTC by xavierlefevre

2018-04-05 12:44 UTC, tychota requested changes
Point avec Xav pour en discuter !

2018-04-06 08:26 UTC, Minishlink commented on performance/backend/backend-performance-tools.md
> +### iPhone: Simulate a network like LTE, 3G or Edge
You can also install network link conditioner on your mac too (for simulators, it's easier to manipulate than going to the iPhone settings)

2018-06-21 09:02 UTC, Minishlink commented
@xavierlefevre Tu peux parler de monitoring avec [Firebase performance monitoring](https://firebase.google.com/docs/perf-mon/) et Apollo Engine aussi :)

2018-06-21 16:00 UTC, tychota approved these changes

2018-06-21 16:01 UTC, merged