MO Rebase or merge a branch
bamlab/dev-standards pull request #12
Opened 2017-08-08 17:39 UTC by Arlevoy

@tychota Hello, comme convenu une première version du MO pour rebase ou merge :)

2017-08-09 20:09 UTC, yleflour requested changes

2017-08-09 20:09 UTC, yleflour commented on git/merge-or-rebase-a-branch.md
> +
Why so much space?

2017-08-09 20:09 UTC, yleflour commented on git/merge-or-rebase-a-branch.md
> +<p>The difference with the merge solution above, it that it will create new commits into your `my-feature` for each commits in `master` and give you a much cleaner project history. </p>
`<p>` is useless

2017-08-09 20:09 UTC, yleflour commented on git/merge-or-rebase-a-branch.md
> +<br/>
useless html tag

2017-08-09 20:09 UTC, yleflour commented on git/merge-or-rebase-a-branch.md
> +<p> It gives you a new “merge commit” in the feature branch that ties together the histories of both branches. </p>
html tag

2017-08-09 20:09 UTC, yleflour commented on git/merge-or-rebase-a-branch.md
> +<p> It's nice because it is a non-destructive operation but if your `master` branch is very active, you might quickly have a new commits including a lot of changes and this will pollute your history
html tag

2017-08-22 16:14 UTC, Arlevoy commented
@yleflour J'ai fait un nouveau commit avec les modifs requises ;)

2017-08-24 07:44 UTC, yleflour approved these changes

2017-08-24 07:44 UTC, merged