Improve front performance standard
bamlab/dev-standards pull request #142
Opened 2018-07-09 12:15 UTC by thibautguedou3

2018-07-10 16:08 UTC, xavierlefevre requested changes

2018-07-10 16:08 UTC, xavierlefevre commented on SUMMARY.MD
> +    - [[Standard] React Native performance](/performance/front/react-native-performance.s.md)
Pour le moment on a mis les learnings/best practices dans la partie : `Now that you investigated, can we help you?`

Si ton objectif c'est que ce soit des standards, et pas que l'on s'y attarde après avoir eu des pbs, changeons le titre, et mettons les avant :

1. Performance standards: **What you should know in order to have performing applications**
2. Performance issues: **How to investigate**
3. Performance control: **How to make sure that your app stays performing with time**

A ce moment là on met dans le 1. ta partie, et mes autres learnings, et celui de Justine

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/how-to-investigate-performance.mo.md
> +Proceed by dichotomy: cut your app in multiple pieces in order to find out where the problem comes from. For example, literally remove some components or pages!
It's not really part of the why this, but more as a global tip on the steps part

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/how-to-investigate-performance.mo.md
> +- Put some `console.count('my component')` in your components' render methods in order to measure the number of renders
You could group the solutions by what they teach you.

If you wanna know the number of renders of one component, it's not the same as not knowing what to look for, or looking for what function takes more time

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/how-to-investigate-performance.mo.md
> +- Put some `console.count('my component')` in your components' render methods in order to measure the number of renders
If I have performance issues and I fall on this article, I won't know what to use right away...

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/react-native-performance.s.md
> +# [Standard] Create performant React Native application
je dirais "performing"

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/react-native-performance.s.md
> +In order to have an efficient application from the get-go, respect the following standards.
Because a few seconds of page render, a laggy chart display or a buggy animation makes you lose customers, those tips will help you avoid that before it even happens.

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/react-native-performance.s.md
> +You don't need to apply every of these standards right away (that would be premature optimization), but as your technical experience grows, you should adopt them along the way.
I would do like that :

```markdown
> Side note: You don't need to apply every of these standards right away (that would be premature optimization), but as your technical experience grows, you should adopt them along the way.
```

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/react-native-performance.s.md
> +- Use an up-to-date version of your dependencies, and first and foremost:
how to do that ? I think we have a standard here explaining how to update RN

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/react-native-performance.s.md
> +- Don't use images that are unnecessary big. Dynamic resizing is very inefficient on Android. Resize them to 1x 2x 3x flavors (`img.png`, `img@2x.png`, `img@3x.png`) and use them normally (`require('
`unnecessarily`

In which case use this ? If images are "Huge" ?

2018-07-10 16:08 UTC, xavierlefevre commented on performance/front/react-native-performance.s.md
> +- Do not request your data to often: if it changes every hour, do not perform the same request every minutes, it will trigger useless renders and waste ressources.
As started above, I believe each point deserves its own little section, and explanation **why** and **when** use them.

2018-07-10 16:08 UTC, xavierlefevre commented on performance/performance-decision-flow.s.md
> +2.  [Investigate performance issues](/performance/front/how-to-investigate-performance.mo.md)
Here you put it in the right place, but not in the readme.md

2018-07-14 10:27 UTC, Minishlink commented on performance/front/how-to-investigate-performance.mo.md
> +- Put some `console.count('my component')` in your components' render methods in order to measure the number of renders
Je pense qu'il faut garder une liste simple des outils dispos comme ici pour avoir en un clin d'oeil la totalité des outils dispos

La liste peut devenir un tableau pour être plus claire mais je pense que c'est vraiment important d'avoir quelque chose qui te donne un résumé très très rapidement => cela adresse les besoins des développeurs "expérimentés" (qui veulent une espèce de checklist rapide) C'est pour ça que j'avais fait un seul fichier à la base, je voulais quelque chose qui soit lisible/scannable en < 1min 

Cette liste peut linker vers d'autres MO d'ailleurs qui décrivent plus en détail le pourquoi et comment de chacun des outils => cela adresserait les besoins des "nouveaux" développeurs

2018-07-14 10:27 UTC, Minishlink commented on performance/front/react-native-performance.s.md
> +# [Standard] Create performant React Native application
C'est un standard et non un MO, "React Native performance" suffit

2018-07-14 10:27 UTC, Minishlink commented on performance/front/react-native-performance.s.md
> +- Do not request your data to often: if it changes every hour, do not perform the same request every minutes, it will trigger useless renders and waste ressources.
Du coup pareil qu'en haut et les mêmes raisons: bonne idée pour des sections / des MO linkés, mais garder cette liste de résumé

2018-07-14 10:27 UTC, Minishlink commented on performance/front/react-native-performance.s.md
> +- Don't use images that are unnecessary big. Dynamic resizing is very inefficient on Android. Resize them to 1x 2x 3x flavors (`img.png`, `img@2x.png`, `img@3x.png`) and use them normally (`require('
On peut spécifier ça dans le futur MO linké : c'est trop grand si la taille de l'image en 1x est plus grande que la taillé spécifiée/utiliée dans React Native

2018-07-24 12:46 UTC, merged