MO: deploy script
bamlab/dev-standards pull request #16
Opened 2017-08-16 17:08 UTC by xavierlefevre

2017-08-17 09:32 UTC, Minishlink reviewed
There's some more goodies with this script 
(mandatory flag, forcing deployment/prevent deployment if Git repo is not clean, default changelog that can be changed) https://github.com/Minishlink/DailyScrum/blob/staging/bin/code-push.sh

2017-08-17 09:32 UTC, Minishlink commented on react-native/setup/deploy-script.mo.md
> +# [MO] Add a deploy script to your app
Required time is missing

2017-08-17 09:32 UTC, Minishlink commented on react-native/setup/deploy.sh
> +  read -r -p "Did you bump the versions in fastlane/.env [y/N] " response
Only required if native code has changed ;)

2017-08-17 09:32 UTC, Minishlink commented on react-native/setup/deploy.sh
> +      code-push release-react -d Staging investo-ios ios -m --targetBinaryVersion $IOS_VERSION --des "$MESSAGE"
Project name should be in a env var or as a placeholder :o (this repo is public)

2017-08-17 12:45 UTC, yleflour requested changes

2017-08-17 12:45 UTC, yleflour commented on react-native/setup/deploy.sh
> +      code-push release-react -d Staging investo-ios ios -m --targetBinaryVersion $IOS_VERSION --des "$MESSAGE"
project name, please commit --amend

2017-08-17 12:45 UTC, yleflour commented on react-native/setup/deploy.sh
> +      code-push release-react -d Staging investo-android android -m --targetBinaryVersion $ANDROID_VERSION_NAME --des "$MESSAGE"
same

2017-08-21 18:07 UTC, xavierlefevre commented
@yleflour @Minishlink : pourriez rechecker ?

@Minishlink : j'ai pris la question "What's the changelog?" et j'ai enlevé : "Did you bump?" pour le moment

2017-08-23 15:24 UTC, merged