add deploy proj to prod
bamlab/dev-standards pull request #3
Opened 2017-07-27 18:57 UTC by xavierlefevre

2017-07-27 22:58 UTC, yleflour requested changes

2017-07-27 22:58 UTC, yleflour commented on react-native/setup/deploy-project-to-production.md
> +- The App Id for this environment: `com.bnp.<ProjectName>.production`
nope and please commit --amend --no-edit

2017-07-27 22:58 UTC, yleflour commented on react-native/setup/deploy-project-to-production.md
> +- Your git repo for match: `git@github.com:bamlab/certificates.git`
Nope, repo is public

2017-07-28 07:41 UTC, xavierlefevre commented on react-native/setup/deploy-project-to-production.md
> +- The App Id for this environment: `com.bnp.<ProjectName>.production`
haha :)

2017-07-28 07:42 UTC, xavierlefevre commented on react-native/setup/deploy-project-to-production.md
> +- Your git repo for match: `git@github.com:bamlab/certificates.git`
... yes, pas pensé, mais c'est aussi sur le MO deploy to staging :)
je l'enlève

2017-07-28 07:49 UTC, tychota approved these changes

2017-07-28 07:51 UTC, tychota commented on react-native/setup/deploy-project-to-production.md
> +- Your git repo for match: `git@github.com:bamlab/certificates.git`
Le repo est public mais l'info est pas secrète contrairement à ce que j'ai remove. L'organisation est bamlab et le repo s'appelle toujours certificates.

Je pense que c'est pas choquant car on ajoute pas d'info.

2017-07-31 09:53 UTC, Almouro commented
Could be merged with https://bamtech.facebook.com/notes/dev/mode-op%C3%A9ratoire-mise-en-prod/1551396194926250/ in a later PR?

2017-08-01 13:14 UTC, yleflour commented
@Almouro This repo is public, no confidential elements should be mentionned

2017-08-01 13:14 UTC, yleflour approved these changes

2017-08-01 13:14 UTC, yleflour approved these changes

2017-08-01 13:15 UTC, yleflour commented
@xavierlefevre The **redacted tags** should be eventually replaced with placeholders where applicable

2017-08-01 13:15 UTC, merged