Add MO how to use HTTP protocol in API calls and images in iOS
bamlab/dev-standards pull request #33
Opened 2017-09-18 17:35 UTC by juliennassar

2017-09-18 17:37 UTC, Almouro commented on react-native/use_http_links_in_react_native.mo.md
> +            source={{ uri: workspace.pictureUrl }}
tu pourrais mettre directement le lien vers l'image pour qu'on puisse tester ? :)
et ça éviterait l'explication en-dessous

2017-09-18 17:38 UTC, Almouro commented on react-native/use_http_links_in_react_native.mo.md
> +If you reloading your app it will not work, you modified a Native element, so you need to rebuild the native part as well
modified native code

2017-10-04 12:11 UTC, tychota approved these changes
Ok for me after those minor changes.

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +- [ ] Have a React Native application
Have a React Native application **(using + link to CRNA or other dev standard)**

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +## Prerequisites
How much time does it takes ?

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +<br />
<br/> a supprimer

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +<img src="https://user-images.githubusercontent.com/13121639/30554696-b92edad0-9ca5-11e7-93f0-7b41f51f8dfc.png" width="300">
`![](https://user-images.githubusercontent.com/13121639/30554696-b92edad0-9ca5-11e7-93f0-7b41f51f8dfc.png)`

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +```html
xml

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +As I said earlier, by default iOS forbids calls using http protocol. Normally you should use secured http protocol (https), if you don't have that opportunity, you have to allow the domain using http
~~As I said earlier,~~

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +If you reloading your app it will not work, you modified Native code, so you need to rebuild the native part as well
That should be a check

```
> Check : Rebuild and it works
```

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +disclaimer : The design isn't implemented yet ;)
Not necessary, it add noise.

2017-10-04 12:11 UTC, tychota commented on react-native/use_http_links_in_react_native.mo.md
> +## Steps
How much time does it takes ?

2017-10-04 12:12 UTC, tychota commented
Ok after minor changes !

2017-10-04 12:12 UTC, tychota requested changes
Should be included in readme.

2017-10-09 19:39 UTC, juliennassar commented on react-native/use_http_links_in_react_native.mo.md
> +<img src="https://user-images.githubusercontent.com/13121639/30554696-b92edad0-9ca5-11e7-93f0-7b41f51f8dfc.png" width="300">
si je mets ça l'image devient trop grande :/

2017-10-09 20:07 UTC, tychota commented
Il faut encore ajouter le standard au readme, mais sinon c'est bon.

2017-10-09 20:08 UTC, tychota commented
En fait c'est bon.

2017-10-09 20:08 UTC, tychota approved these changes

2017-10-09 20:08 UTC, merged