Add flow standard
bamlab/dev-standards pull request #38
Opened 2017-10-02 14:18 UTC by tychota

2017-10-02 14:56 UTC, 4ian commented on flowtype/flowtype.s.md
> +- it give you autocompletes
*autocompletion

2017-10-02 14:56 UTC, 4ian commented on flowtype/flowtype.s.md
> +- it successfully replace unit tests for some tasks, like ensuring that the differents parts of the app, remains in sync with each others.
replaces

2017-10-02 14:56 UTC, 4ian commented on flowtype/flowtype.s.md
> +Flowtype is awesome.:
awesome:

2017-10-02 16:33 UTC, 4ian commented
Les pratiques préconisées me semblent bien !

2017-10-03 08:27 UTC, yleflour requested changes

2017-10-03 08:27 UTC, yleflour commented on dangerfile.js
> +  if (!fileContent.match(/Bad Examples?/i)) fail(`**${fileUrl}**: You failed to mention a *Bad Examples*`);
passe le en warn, trop relou sinon

2017-10-03 08:27 UTC, yleflour commented on dangerfile.js
> +  if (!fileContent.match(/Good Examples?/i)) fail(`**${fileUrl}**: You failed to mention a *Good Examples* `);
passe le en warn, trop relou sinon

2017-10-03 08:27 UTC, yleflour commented on flowtype/flowtype.s.md
> +#### ✅ **Good example**
Start with bad then good

2017-10-30 13:33 UTC, merged