MO screen orientation
bamlab/dev-standards pull request #53
Opened 2017-10-22 11:34 UTC by juliennassar

2017-10-26 18:03 UTC, Almouro requested changes

2017-10-26 18:03 UTC, Almouro commented on react-native/react/screen-orientation.mo.md
> +Then kill your packager and rebuild your app with `react-navite run-ios`
you don't have to kill your packager

2017-10-26 18:03 UTC, Almouro commented on react-native/react/screen-orientation.mo.md
> +ex : In this example I only allowed Portrait mode
no space before `:`

2017-10-26 18:03 UTC, Almouro commented on react-native/react/screen-orientation.mo.md
> +You may sometimes need to control the screen orientation of your app. You might want to fix your screen orientation to portrait mode only, or, depending on the page you are in, you might want to spec
do you have example of changing orientation for some screens?
I can think of UGC: changing orientation for full screen videos only

2017-10-26 18:03 UTC, Almouro commented on react-native/react/screen-orientation.mo.md
> +`yarn add react-native-orientation``
`` -> `

2017-10-26 18:03 UTC, Almouro commented on react-native/react/screen-orientation.mo.md
> +and follow documentation ;)
can you give an example? For instance unlocking orientation for a single screen?

2018-01-17 09:13 UTC, tychota commented
I pinged @juliennassar : goal merge this this week.

2018-04-04 08:47 UTC, tychota commented
No Activity feel free to reopen. Archiving.

2018-04-04 08:47 UTC, closed without merging