Mo overflow android
bamlab/dev-standards pull request #54
Opened 2017-10-24 14:55 UTC by yassinecc

2017-10-30 15:43 UTC, tychota requested changes

2017-10-30 15:43 UTC, tychota commented on README.MD
> +- [[MO] Enable component overflow on Android](/react-native/react/enable-overflow-android.mo.md)
Nope. Pas de replacement

2017-10-30 15:43 UTC, tychota commented on react-native/react/enable-overflow-android.mo.md
> +![Without uncle](../../assets/withoutUncle.png)
image passe pas.

2017-10-30 15:43 UTC, tychota commented on react-native/react/enable-overflow-android.mo.md
> +    marginTop: - OVERLAP_HEIGHT
-O pas - O

2017-10-30 15:43 UTC, tychota commented on react-native/react/trigger-action-on-props-update.m.md
> +# Trigger action on props update with componentWillReceiveProps
Pourquoi y'a 2 standards en 1 ?

2018-01-05 18:16 UTC, merged

2018-01-05 18:17 UTC, louiszawadzki commented
@yassinecc c'est mergé ;)