first draft to a new MO: deploy django to aws
bamlab/dev-standards pull request #63
Opened 2017-11-13 11:19 UTC by xavierlefevre

2017-11-16 17:24 UTC, tychota requested changes
Hello @xavierlefevre, I fixed a bug I introduced working on dangerfiles: can you rebase https://github.com/bamlab/dev-standards/commit/6ebbc236cd6d51410519f78c03c62a10e48effc3

I can then help you reviewing.

(note that your file has to be .mo.md or .s.md)

2017-11-21 13:15 UTC, Samox commented on backend/django/deploy-to-aws.md
> +  - Give a general name to your instance, generaly the name of the project/company
example: name_of_project-staging

2017-11-21 13:17 UTC, Samox commented on backend/django/deploy-to-aws.md
> +  - Give a general name to your instance, generaly the name of the project/company
ah nan je retire c'est pas la ^^

2017-11-21 13:21 UTC, Samox commented on backend/django/deploy-to-aws.md
> +- TODO
Now that you have deployed once, on your host you should have the credentials for AWS (`cat ~/.aws/config`). 
To create a super user you will have to connect directly to the machine in order to run ./manage.py createsuperuser.

To ssh to your EC2 machine run `eb ssh [PUT YOUR INSTANCE NAME IF NOT BY DEFAULT]` 

Then on the machine go to the root of the project:
-`cd /opt/python/current`
Add the python environment:
- `source ./env`
Run the createuser command
- `cd /app`
- `./manage.py createsuperuser`

2017-11-26 18:58 UTC, xavierlefevre commented
@tychota ! rebased and renamed the file. @Samox reviewed the PR, what about merging it quickly, and iterating 💃

2017-11-27 13:40 UTC, Samox approved these changes

2017-11-27 13:55 UTC, Samox approved these changes

2017-11-29 13:16 UTC, tychota approved these changes

2017-11-29 13:16 UTC, tychota commented on backend/django/deploy-to-aws.mo.md
> +## Prerequisites
Time

2017-11-29 13:16 UTC, tychota commented on backend/django/deploy-to-aws.mo.md
> +- Check: You can verify on the AWS website that each server peace has been created (EB, RDS, S3, EC2)
> Checks

2017-11-29 13:16 UTC, tychota commented on backend/django/deploy-to-aws.mo.md
> +
> Check you can access the admin

2017-11-29 14:06 UTC, merged