[MO] Deploy project to production - android
bamlab/dev-standards pull request #65
Opened 2017-11-15 17:23 UTC by yassinecc

2017-11-16 17:27 UTC, tychota requested changes
Hello @yassinecc  , I fixed a bug I introduced working on dangerfiles: can you rebase https://github.com/bamlab/dev-standards/commit/6ebbc236cd6d51410519f78c03c62a10e48effc3

I can then help you reviewing.

2017-11-16 19:13 UTC, tychota requested changes

2017-11-16 19:13 UTC, tychota commented on react-native/setup/deploy-to-production-android.mo.md
> +```bash
Extra ligne before code, else gitbook will behave weirdly.

2017-11-16 19:13 UTC, tychota commented on react-native/setup/deploy-to-production-android.mo.md
> +### 6. Make your app available for beta testing
Where are part 3 -> 6

2017-11-27 21:20 UTC, xavierlefevre commented
@yassinecc le rebase c'est bien passé ? car je ne vois plus aucun fichier modifié dans la PR :O

2018-02-12 12:40 UTC, yassinecc commented
@tychota Can you review this PR?

2018-02-13 18:27 UTC, Minishlink commented on react-native/setup/deploy-to-production-android.mo.md
> +* Click on `Manage Beta` then `Create release` and upload the APK generated from the build process. This file is located at `android/app/build/outputs/apk/app-release.apk`
This can be automated using fastlane ;)

2018-04-04 08:55 UTC, tychota approved these changes

2018-04-04 08:55 UTC, merged