Add Redux repos and standards
bamlab/dev-standards pull request #7
Opened 2017-07-31 18:30 UTC by Almouro

2017-07-31 23:00 UTC, tychota requested changes

2017-07-31 23:00 UTC, tychota commented on redux/write-your-own-saga-effects.mo.md
> +- [ ] Redux installed
How ? Need some links !

2017-07-31 23:00 UTC, tychota commented on redux/write-your-own-saga-effects.mo.md
> +- [ ] Redux saga installed
Idem

2017-07-31 23:00 UTC, tychota commented on redux/write-your-own-saga-effects.mo.md
> +## Reproducible example *(~3min)*
why is it cool ?

why not `yield* authenticatedCall(..)`

2017-08-31 17:09 UTC, Almouro commented on redux/write-your-own-saga-effects.mo.md
> +- [ ] Redux installed
Really?

2017-08-31 17:09 UTC, Almouro commented on redux/write-your-own-saga-effects.mo.md
> +- [ ] Redux saga installed
Really?

2017-10-04 12:40 UTC, tychota commented
Closing as too old PR. Feel free to reopen later.

This PR use to add a standard but only points to a repository. Please put back a small artcile MO withh a context, and some steps with checks.

2017-10-04 12:40 UTC, closed without merging