Update *[MO] Deploy to staging* with AppCenter
bamlab/dev-standards pull request #75
Opened 2017-12-11 12:53 UTC by felixmeziere

2017-12-15 17:14 UTC, louiszawadzki commented
@felixmeziere our current flow still uses Hockey App, I suggest we keep the MO as it is until mid-2018 as 

> We’re working on the specific timing, but currently we expect the option to fully migrate off of HockeyApp to App Center to be available in mid-2018.

(https://hockeyapp.net/appcenter/faq/)

2017-12-15 17:33 UTC, tychota reviewed
Your file is named:

"react-native/setup/setup-and-deploy-new-project-to-staging.md"

where it should be:

react-native/setup/setup-and-deploy-new-project-to-staging.**mo**.md

I know that you only have modified it, but now that we have a poka yoke to catch this, I would like you to fix it.

2018-01-03 17:42 UTC, tychota commented
ping @felixmeziere !

2018-01-24 18:18 UTC, felixmeziere commented
@louiszawadzki I think we should do the move before they migrate completely, this is the point of the standard. We need to be ready for when that happens.
We are already using AppCenter in the UK and using it is seamless.
Have you noticed any feature that you used in HockeyApp but missing in AppCenter?

Also, the idea that we mentioned with Yann was to rename this standard to "[MO] Deploy to staging with AppCenter" and have the two in parallel for a little while, then delete the current one.

Are you ok with this?

@tychota I'll address the change ASAP

2018-01-24 18:41 UTC, tychota commented
@felixmeziere I would like instead having a "[MO] Deploy to staging" which points to this standard but move the old standard to "[MO] Deploy to staging with HockeyApp".

For the depreciation you can use hints. The syntax is something like:

for `deploy-to-staging-with-hockey.mo.md`:

```
# [MO] Deploy to staging with HockeyApp

{% hint style='warning' } **DEPRECIATION**

This standard has been deprecated by [@felixmeziere](link/to/your/github/profile) on January 24 in favour of [[MO] Deploy to staging](link to the new standard).

**Reason**: hockeyapp is mean to be deprecated by appcenter is the new hockey, 100% compatible with hockey.

{% endhint %}

/// rest of the standard
```

for `deploy-to-staging.mo.md`:

```
# [MO] Deploy to staging with HockeyApp

{% hint style='warning' } **NOTE**

This standard replaces [[MO] Deploy to staging with hockeyapp](link to the old standard), deprecated by [@felixmeziere](link/to/your/github/profile) on January 24.

**Reason**: hockeyapp is mean to be deprecated by appcenter is the new hockey, 100% compatible with hockey.

{% endhint %}

/// rest of the standard
```

2018-01-24 18:41 UTC, tychota commented
(Wrong button sorry)

2018-01-25 14:42 UTC, felixmeziere commented
Thanks! I'll do it.
Have you solved the problem of the link for the PO?

2018-01-27 21:06 UTC, tychota requested changes
It is very good @felixmeziere. Just some markdown nits and danger auto-checks.

![image](https://user-images.githubusercontent.com/13785185/35476313-17bf6cd0-03ae-11e8-8aaa-82f552b499ae.png)


You shall had owner to the standards (you can add yourself to the new and yann to the old).

And you hall double check that every standard are included in the readme and the summary file (even the deprecated one), else gitbook is not going to found them.

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging-with-hockeyapp.mo.md
> +**Reason**: HockeyApp is meant to be deprecated by AppCenter. AppCenter is the new HockeyApp and there is [no loss of functionality](http://blog.m33.network/2017/09/react-native-devops-2-0-overview-o
Is the link accessible to public (not M33) ?

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging-with-hockeyapp.mo.md
> +**Reason**: HockeyApp is meant to be deprecated by AppCenter. AppCenter is the new HockeyApp and there is [no loss of functionality](http://blog.m33.network/2017/09/react-native-devops-2-0-overview-o
And you can put @yleflour as owner of the deprecated standard.

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +{% hint style='warning' } **NOTE**
You can put yourself as owner of the new standard (see other standards to see the format).

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +> :warning: Remember to commit after each step
The :warning: can be changed to 

{% hint style='warning %}

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +```
bash

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +```
bash

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +```
Bash

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +```
bash and empty line between title and code

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +```
bash and empty line between title and code

2018-01-27 21:06 UTC, tychota commented on react-native/setup/setup-and-deploy-new-project-to-staging.mo.md
> +- For each app (Android + iOS)
Empty line

2018-01-29 10:57 UTC, felixmeziere commented on react-native/setup/setup-and-deploy-new-project-to-staging-with-hockeyapp.mo.md
> +**Reason**: HockeyApp is meant to be deprecated by AppCenter. AppCenter is the new HockeyApp and there is [no loss of functionality](http://blog.m33.network/2017/09/react-native-devops-2-0-overview-o
no the link isn't accessible to public.

2018-01-29 11:16 UTC, merged